#!/usr/bin/env python3
"""Generate apps/epic-everywhere/config.js from catalog.full.json + live payment links."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "epic-desk" / "catalog.full.json"
LIVE = ROOT / "epic-desk" / "catalog.live.json"
OUT = ROOT / "apps" / "epic-everywhere" / "config.js"


def money(cents: int) -> str:
    if cents % 100 == 0:
        return f"${cents // 100:,}"
    return f"${cents / 100:.2f}".replace(".00", "")


def main() -> int:
    full = json.loads(CATALOG.read_text())
    live = {}
    if LIVE.exists():
        live_doc = json.loads(LIVE.read_text())
        live = live_doc.get("skus") or {}

    skus_out = []
    for s in full["skus"]:
        sid = s["id"]
        link = None
        if isinstance(live.get(sid), dict):
            link = live[sid].get("payment_link")
        entry = {
            "id": sid,
            "layer": s["layer"],
            "vertical": s.get("vertical", "general"),
            "name": s["name"],
            "price": money(int(s["amount_cents"])),
            "amount_cents": int(s["amount_cents"]),
            "blurb": s["blurb"],
            "paymentLink": link,
        }
        if s.get("featured"):
            entry["featured"] = True
        if s.get("phase"):
            entry["phase"] = s["phase"]
        if s.get("recurring"):
            entry["recurring"] = s["recurring"]
        skus_out.append(entry)

    config = {
        "brand": "Epic Tech AI",
        "product": "Epic Everywhere",
        "contactEmail": "epictechai@gmail.com",
        "xUrl": "https://x.com/EpicTechAI",
        "successPath": "./success.html",
        "legalPath": "./legal/",
        "catalogVersion": full.get("version"),
        "skuCount": len(skus_out),
        "skus": skus_out,
    }

    body = (
        "/**\n"
        " * AUTO-GENERATED by epic-desk/scripts/generate_config.py — do not hand-edit SKUs.\n"
        " * Payment links come from epic-desk/catalog.live.json (public URLs only).\n"
        " */\n"
        f"window.EPIC_CONFIG = {json.dumps(config, indent=2)};\n"
    )
    OUT.write_text(body)
    linked = sum(1 for s in skus_out if s.get("paymentLink"))
    print(f"Wrote {OUT} with {len(skus_out)} SKUs ({linked} with payment links)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
