/**
 * AUTO-GENERATED by epic-desk/scripts/generate_config.py — do not hand-edit SKUs.
 * Payment links come from epic-desk/catalog.live.json (public URLs only).
 */
window.EPIC_CONFIG = {
  "brand": "Epic Tech AI",
  "product": "Epic Everywhere",
  "contactEmail": "epictechai@gmail.com",
  "xUrl": "https://x.com/EpicTechAI",
  "successPath": "./success.html",
  "legalPath": "./legal/",
  "catalogVersion": "2026-07-13",
  "skuCount": 66,
  "skus": [
    {
      "id": "human-ticket",
      "layer": "micro",
      "vertical": "community",
      "name": "Human / entry ticket",
      "price": "$0.99",
      "amount_cents": 99,
      "blurb": "Low-friction entry pass.",
      "paymentLink": "https://buy.stripe.com/eVq3cwaYN91Y5928nw0Fi0d"
    },
    {
      "id": "tip-3",
      "layer": "micro",
      "vertical": "community",
      "name": "Support tip $3",
      "price": "$3",
      "amount_cents": 300,
      "blurb": "Tip the CS desk \u2014 keeps free guidance alive.",
      "paymentLink": "https://buy.stripe.com/9B6cN6c2Rdie8le7js0Fi0e"
    },
    {
      "id": "tip-5",
      "layer": "micro",
      "vertical": "community",
      "name": "Support tip $5",
      "price": "$5",
      "amount_cents": 500,
      "blurb": "Bigger tip for deeper free help.",
      "paymentLink": "https://buy.stripe.com/7sYeVe9UJfqmdFyavE0Fi0f"
    },
    {
      "id": "ai-starter-pack",
      "layer": "micro",
      "vertical": "general",
      "name": "AI Starter Pack",
      "price": "$2.99",
      "amount_cents": 299,
      "blurb": "10 guided prompts + personal starter plan.",
      "paymentLink": "https://buy.stripe.com/28E7sM9UJba61WQdHQ0Fi0g"
    },
    {
      "id": "ai-starter-pack-pro",
      "layer": "micro",
      "vertical": "general",
      "name": "AI Starter Pack Pro",
      "price": "$7.99",
      "amount_cents": 799,
      "blurb": "30 prompts + role plan + 48h text follow-up.",
      "paymentLink": "https://buy.stripe.com/00w14o8QF3HE1WQbzI0Fi0h"
    },
    {
      "id": "cs-text-burst",
      "layer": "micro",
      "vertical": "general",
      "name": "Text CS Burst (24h)",
      "price": "$4.99",
      "amount_cents": 499,
      "blurb": "24h text customer success on your setup.",
      "paymentLink": "https://buy.stripe.com/28E8wQd6V5PM8le9rA0Fi0i",
      "featured": true
    },
    {
      "id": "cs-text-burst-72",
      "layer": "micro",
      "vertical": "general",
      "name": "Text CS Burst (72h)",
      "price": "$9.99",
      "amount_cents": 999,
      "blurb": "3-day text CS window for harder setups.",
      "paymentLink": "https://buy.stripe.com/dRmcN62shcea0SM6fo0Fi0j"
    },
    {
      "id": "workflow-fix",
      "layer": "micro",
      "vertical": "general",
      "name": "Workflow Fix",
      "price": "$9",
      "amount_cents": 900,
      "blurb": "One pain \u2192 one reusable AI workflow.",
      "paymentLink": "https://buy.stripe.com/3cI5kE6Ix4LI1WQ5bk0Fi0k",
      "featured": true
    },
    {
      "id": "workflow-fix-3",
      "layer": "micro",
      "vertical": "general",
      "name": "Workflow Fix Bundle (3)",
      "price": "$24",
      "amount_cents": 2400,
      "blurb": "Three workflows for home, work, and side project.",
      "paymentLink": "https://buy.stripe.com/8x23cw8QF0vsgRKgU20Fi0l"
    },
    {
      "id": "credit-5",
      "layer": "micro",
      "vertical": "credits",
      "name": "Credit Pack 5",
      "price": "$5",
      "amount_cents": 500,
      "blurb": "5 credits toward text CS.",
      "paymentLink": "https://buy.stripe.com/fZu14o6IxfqmbxqfPY0Fi0m"
    },
    {
      "id": "credit-10",
      "layer": "micro",
      "vertical": "credits",
      "name": "Credit Pack 10",
      "price": "$10",
      "amount_cents": 1000,
      "blurb": "10 credits toward text CS / future voice.",
      "paymentLink": "https://buy.stripe.com/4gM4gAeaZ7XUgRK9rA0Fi0n"
    },
    {
      "id": "credit-25",
      "layer": "micro",
      "vertical": "credits",
      "name": "Credit Pack 25",
      "price": "$22",
      "amount_cents": 2200,
      "blurb": "25 credits \u2014 best micro value.",
      "paymentLink": "https://buy.stripe.com/00w3cw5Et6TQ5929rA0Fi0o"
    },
    {
      "id": "credit-50",
      "layer": "micro",
      "vertical": "credits",
      "name": "Credit Pack 50",
      "price": "$40",
      "amount_cents": 4000,
      "blurb": "50 credits for power users.",
      "paymentLink": "https://buy.stripe.com/4gM28s2shba6eJCdHQ0Fi0p"
    },
    {
      "id": "prompt-audit",
      "layer": "micro",
      "vertical": "general",
      "name": "Prompt Audit",
      "price": "$7",
      "amount_cents": 700,
      "blurb": "We rewrite your 5 worst prompts into winners.",
      "paymentLink": "https://buy.stripe.com/00waEYgj72DA592dHQ0Fi0q"
    },
    {
      "id": "tool-stack-map",
      "layer": "micro",
      "vertical": "general",
      "name": "Tool Stack Map",
      "price": "$12",
      "amount_cents": 1200,
      "blurb": "Which AI tools you actually need \u2014 one page plan.",
      "paymentLink": "https://buy.stripe.com/bJe28s1oda620SM1Z80Fi0r"
    },
    {
      "id": "student-homework-kit",
      "layer": "micro",
      "vertical": "student",
      "name": "Student Homework Kit",
      "price": "$4.99",
      "amount_cents": 499,
      "blurb": "Subject prompts + integrity-safe study method.",
      "paymentLink": "https://buy.stripe.com/cNicN61odba61WQ47g0Fi0s"
    },
    {
      "id": "student-essay-coach",
      "layer": "micro",
      "vertical": "student",
      "name": "Essay Coach Pack",
      "price": "$9",
      "amount_cents": 900,
      "blurb": "Outline, thesis, revision loop \u2014 you still write it.",
      "paymentLink": "https://buy.stripe.com/5kQ9AUaYNdiefNG0V40Fi0t"
    },
    {
      "id": "student-stem-pack",
      "layer": "micro",
      "vertical": "student",
      "name": "STEM Study Pack",
      "price": "$9",
      "amount_cents": 900,
      "blurb": "Math/science problem-solving with AI, step-by-step.",
      "paymentLink": "https://buy.stripe.com/00w9AUeaZ0vs1WQdHQ0Fi0u"
    },
    {
      "id": "student-college-apps",
      "layer": "micro",
      "vertical": "student",
      "name": "College Apps AI Kit",
      "price": "$15",
      "amount_cents": 1500,
      "blurb": "Brainstorm + structure essays ethically.",
      "paymentLink": "https://buy.stripe.com/bJeaEYc2Rfqm30U33c0Fi0v"
    },
    {
      "id": "parent-safety-kit",
      "layer": "micro",
      "vertical": "parent",
      "name": "Parent AI Safety Kit",
      "price": "$4.99",
      "amount_cents": 499,
      "blurb": "Family rules, tools, and homework boundaries.",
      "paymentLink": "https://buy.stripe.com/28E4gA7MB1zw8le0V40Fi0w"
    },
    {
      "id": "parent-homework-coach",
      "layer": "micro",
      "vertical": "parent",
      "name": "Parent Homework Coach",
      "price": "$9",
      "amount_cents": 900,
      "blurb": "Help your kid use AI without doing it for them.",
      "paymentLink": "https://buy.stripe.com/3cI00k3wl5PM0SM33c0Fi0x"
    },
    {
      "id": "parent-device-setup",
      "layer": "micro",
      "vertical": "parent",
      "name": "Family Device AI Setup",
      "price": "$12",
      "amount_cents": 1200,
      "blurb": "Phone/laptop AI apps configured for the household.",
      "paymentLink": "https://buy.stripe.com/8x2dRad6Vcea30U6fo0Fi0y"
    },
    {
      "id": "teacher-classroom-kit",
      "layer": "micro",
      "vertical": "teacher",
      "name": "Teacher Classroom Kit",
      "price": "$9",
      "amount_cents": 900,
      "blurb": "One week of AI lesson assist prompts + policy notes.",
      "paymentLink": "https://buy.stripe.com/7sYeVe8QF4LIfNGcDM0Fi0z"
    },
    {
      "id": "teacher-rubric-pack",
      "layer": "micro",
      "vertical": "teacher",
      "name": "Rubric & Feedback Pack",
      "price": "$12",
      "amount_cents": 1200,
      "blurb": "Faster feedback loops that stay human-led.",
      "paymentLink": "https://buy.stripe.com/fZubJ21od0vs1WQavE0Fi0A"
    },
    {
      "id": "teacher-pd-micro",
      "layer": "micro",
      "vertical": "teacher",
      "name": "Teacher PD Micro",
      "price": "$19",
      "amount_cents": 1900,
      "blurb": "90-min async PD plan you can run with peers.",
      "paymentLink": "https://buy.stripe.com/7sY7sM5Etfqm9pidHQ0Fi0B"
    },
    {
      "id": "founder-offer-kit",
      "layer": "micro",
      "vertical": "founder",
      "name": "Founder Offer Kit",
      "price": "$15",
      "amount_cents": 1500,
      "blurb": "Positioning + offer page outline with AI.",
      "paymentLink": "https://buy.stripe.com/28EeVe3wl2DAgRK0V40Fi0C"
    },
    {
      "id": "founder-outreach-pack",
      "layer": "micro",
      "vertical": "founder",
      "name": "Outreach Pack",
      "price": "$12",
      "amount_cents": 1200,
      "blurb": "20 personalized outreach templates + system.",
      "paymentLink": "https://buy.stripe.com/5kQ7sMaYNdie30U5bk0Fi0D"
    },
    {
      "id": "founder-support-bot-plan",
      "layer": "micro",
      "vertical": "founder",
      "name": "Support Bot Plan",
      "price": "$19",
      "amount_cents": 1900,
      "blurb": "CS macros + AI assist design for your product.",
      "paymentLink": "https://buy.stripe.com/5kQ3cwgj76TQfNGeLU0Fi0E"
    },
    {
      "id": "smb-email-overhaul",
      "layer": "micro",
      "vertical": "smb",
      "name": "Email Overhaul",
      "price": "$9",
      "amount_cents": 900,
      "blurb": "Rewrite your core business emails with AI.",
      "paymentLink": "https://buy.stripe.com/14A6oIgj7ba65920V40Fi0F"
    },
    {
      "id": "smb-review-replies",
      "layer": "micro",
      "vertical": "smb",
      "name": "Review Reply Pack",
      "price": "$7",
      "amount_cents": 700,
      "blurb": "Google/Yelp reply system for local business.",
      "paymentLink": "https://buy.stripe.com/6oU5kE9UJguq6d633c0Fi0G"
    },
    {
      "id": "smb-sop-pack",
      "layer": "micro",
      "vertical": "smb",
      "name": "SOP Starter Pack",
      "price": "$15",
      "amount_cents": 1500,
      "blurb": "3 SOPs drafted with AI for your ops.",
      "paymentLink": "https://buy.stripe.com/7sY4gA9UJ1zw0SMbzI0Fi0H"
    },
    {
      "id": "creator-content-engine",
      "layer": "micro",
      "vertical": "creator",
      "name": "Content Engine Micro",
      "price": "$12",
      "amount_cents": 1200,
      "blurb": "7-day content system for X/Shorts/LinkedIn.",
      "paymentLink": "https://buy.stripe.com/4gM6oI3wl3HEgRKcDM0Fi0I"
    },
    {
      "id": "creator-script-pack",
      "layer": "micro",
      "vertical": "creator",
      "name": "Script Pack (10)",
      "price": "$9",
      "amount_cents": 900,
      "blurb": "Ten short-form scripts in your voice.",
      "paymentLink": "https://buy.stripe.com/4gMfZi9UJ91Y9pi1Z80Fi0J"
    },
    {
      "id": "career-resume-pack",
      "layer": "micro",
      "vertical": "career",
      "name": "Resume + LinkedIn Pack",
      "price": "$15",
      "amount_cents": 1500,
      "blurb": "AI-assisted resume + profile rewrite.",
      "paymentLink": "https://buy.stripe.com/bJe14o9UJ4LI0SMeLU0Fi0K"
    },
    {
      "id": "career-interview-kit",
      "layer": "micro",
      "vertical": "career",
      "name": "Interview Kit",
      "price": "$12",
      "amount_cents": 1200,
      "blurb": "STAR stories + mock questions with AI.",
      "paymentLink": "https://buy.stripe.com/aFadRa8QF5PMeJCdHQ0Fi0L"
    },
    {
      "id": "career-portfolio-plan",
      "layer": "micro",
      "vertical": "career",
      "name": "Portfolio Plan",
      "price": "$9",
      "amount_cents": 900,
      "blurb": "Ship a portfolio narrative in one weekend.",
      "paymentLink": "https://buy.stripe.com/00w00kaYNemigRK6fo0Fi0M"
    },
    {
      "id": "senior-basics",
      "layer": "micro",
      "vertical": "senior",
      "name": "AI Basics for Adults",
      "price": "$4.99",
      "amount_cents": 499,
      "blurb": "Patient, large-print style starter for non-tech adults.",
      "paymentLink": "https://buy.stripe.com/14A28seaZa62atm8nw0Fi0N"
    },
    {
      "id": "senior-phone-prep",
      "layer": "micro",
      "vertical": "senior",
      "name": "Phone Session Prep",
      "price": "$3",
      "amount_cents": 300,
      "blurb": "Prep worksheet before a phone coaching call.",
      "paymentLink": "https://buy.stripe.com/3cI00kaYNfqmbxqdHQ0Fi0O"
    },
    {
      "id": "phone-15",
      "layer": "session",
      "vertical": "live",
      "name": "Phone coaching 15m",
      "price": "$15",
      "amount_cents": 1500,
      "blurb": "Guided AI setup call.",
      "paymentLink": "https://buy.stripe.com/8x214o6Ix5PMatmbzI0Fi0P",
      "phase": "Phase 2"
    },
    {
      "id": "phone-30",
      "layer": "session",
      "vertical": "live",
      "name": "Phone coaching 30m",
      "price": "$29",
      "amount_cents": 2900,
      "blurb": "Deep-dive coaching call.",
      "paymentLink": "https://buy.stripe.com/aFa3cw9UJ6TQ0SM6fo0Fi0Q",
      "featured": true,
      "phase": "Phase 2"
    },
    {
      "id": "phone-60",
      "layer": "session",
      "vertical": "live",
      "name": "Phone coaching 60m",
      "price": "$55",
      "amount_cents": 5500,
      "blurb": "Full-hour implementation call.",
      "paymentLink": "https://buy.stripe.com/fZu8wQ6Ix7XUatm1Z80Fi0R",
      "phase": "Phase 2"
    },
    {
      "id": "video-tutor-25",
      "layer": "session",
      "vertical": "live",
      "name": "Live video tutor 25m",
      "price": "$25",
      "amount_cents": 2500,
      "blurb": "Screen-share. Do the task together.",
      "paymentLink": "https://buy.stripe.com/14AcN60k9cea5927js0Fi0S",
      "featured": true,
      "phase": "Phase 3"
    },
    {
      "id": "video-tutor-50",
      "layer": "session",
      "vertical": "live",
      "name": "Live video tutor 50m",
      "price": "$49",
      "amount_cents": 4900,
      "blurb": "Project session with reusable pack.",
      "paymentLink": "https://buy.stripe.com/6oUaEYc2Rba644Y6fo0Fi0T",
      "phase": "Phase 3"
    },
    {
      "id": "video-tutor-90",
      "layer": "session",
      "vertical": "live",
      "name": "Live video tutor 90m",
      "price": "$89",
      "amount_cents": 8900,
      "blurb": "Deep build session.",
      "paymentLink": "https://buy.stripe.com/fZueVe7MBba60SM47g0Fi0U",
      "phase": "Phase 3"
    },
    {
      "id": "class-seat",
      "layer": "session",
      "vertical": "live",
      "name": "Group class seat",
      "price": "$12",
      "amount_cents": 1200,
      "blurb": "Weekly AI-for-everyone class.",
      "paymentLink": "https://buy.stripe.com/4gM14o0k97XUatmavE0Fi0V",
      "phase": "Phase 3"
    },
    {
      "id": "class-seat-4pack",
      "layer": "session",
      "vertical": "live",
      "name": "Group class 4-pack",
      "price": "$40",
      "amount_cents": 4000,
      "blurb": "Four class seats.",
      "paymentLink": "https://buy.stripe.com/28E00k5Et4LI9pi1Z80Fi0W",
      "phase": "Phase 3"
    },
    {
      "id": "office-hours-dropin",
      "layer": "session",
      "vertical": "live",
      "name": "Office hours drop-in",
      "price": "$19",
      "amount_cents": 1900,
      "blurb": "Join next open office hours block.",
      "paymentLink": "https://buy.stripe.com/cNiaEY4Ap0vseJC0V40Fi0X",
      "phase": "Phase 2"
    },
    {
      "id": "pilot-landing",
      "layer": "package",
      "vertical": "build",
      "name": "Pilot Landing",
      "price": "$750",
      "amount_cents": 75000,
      "blurb": "One-page site + form on Vercel.",
      "paymentLink": "https://buy.stripe.com/7sY3cw1od4LIbxqcDM0Fi0Y",
      "featured": true
    },
    {
      "id": "pilot-landing-plus",
      "layer": "package",
      "vertical": "build",
      "name": "Pilot Landing Plus",
      "price": "$1,250",
      "amount_cents": 125000,
      "blurb": "Landing + Stripe micros + basic analytics.",
      "paymentLink": "https://buy.stripe.com/7sY28s9UJcea5926fo0Fi0Z"
    },
    {
      "id": "agent-ops-setup",
      "layer": "package",
      "vertical": "build",
      "name": "Agent Ops Setup",
      "price": "$1,500",
      "amount_cents": 150000,
      "blurb": "Slack + Stripe + agent ops wired.",
      "paymentLink": "https://buy.stripe.com/3cIcN64Ap2DA1WQdHQ0Fi10",
      "featured": true
    },
    {
      "id": "agent-ops-setup-pro",
      "layer": "package",
      "vertical": "build",
      "name": "Agent Ops Setup Pro",
      "price": "$3,500",
      "amount_cents": 350000,
      "blurb": "Ops setup + 2 custom workflows + 30d CS.",
      "paymentLink": "https://buy.stripe.com/cNi9AU2sh5PMeJCbzI0Fi11"
    },
    {
      "id": "school-pilot",
      "layer": "package",
      "vertical": "education",
      "name": "School Pilot",
      "price": "$2,500",
      "amount_cents": 250000,
      "blurb": "Classroom AI adoption pilot.",
      "paymentLink": "https://buy.stripe.com/3cI8wQ4Apba6fNG8nw0Fi12",
      "featured": true
    },
    {
      "id": "school-pilot-district",
      "layer": "package",
      "vertical": "education",
      "name": "School Pilot (multi-site)",
      "price": "$7,500",
      "amount_cents": 750000,
      "blurb": "Multi-site pilot + teacher PD outline.",
      "paymentLink": "https://buy.stripe.com/eVq00k8QF3HE7ha1Z80Fi13"
    },
    {
      "id": "creator-brand-kit",
      "layer": "package",
      "vertical": "creator",
      "name": "Creator Brand Kit Build",
      "price": "$990",
      "amount_cents": 99000,
      "blurb": "Positioning, content system, 30-day calendar.",
      "paymentLink": "https://buy.stripe.com/3cIaEY7MB0vs30U33c0Fi14"
    },
    {
      "id": "smb-ai-ops",
      "layer": "package",
      "vertical": "smb",
      "name": "SMB AI Ops Sprint",
      "price": "$1,990",
      "amount_cents": 199000,
      "blurb": "2-week ops automation sprint for local/online SMB.",
      "paymentLink": "https://buy.stripe.com/3cIeVe2sha6244YbzI0Fi15"
    },
    {
      "id": "career-sprint",
      "layer": "package",
      "vertical": "career",
      "name": "Career Sprint",
      "price": "$499",
      "amount_cents": 49900,
      "blurb": "2-week job search system with AI.",
      "paymentLink": "https://buy.stripe.com/dRmcN61od1zw1WQ7js0Fi16"
    },
    {
      "id": "custom-work-deposit",
      "layer": "package",
      "vertical": "build",
      "name": "Custom Work Deposit",
      "price": "$500",
      "amount_cents": 50000,
      "blurb": "Kickoff deposit for scoped custom work.",
      "paymentLink": "https://buy.stripe.com/3cI00k9UJfqmdFyeLU0Fi17"
    },
    {
      "id": "retainer-lite",
      "layer": "package",
      "vertical": "retain",
      "name": "Retainer Lite (mo)",
      "price": "$499",
      "amount_cents": 49900,
      "blurb": "Monthly async CS + 2 workflows.",
      "paymentLink": "https://buy.stripe.com/dRm4gAc2R1zwatmgU20Fi18",
      "recurring": "month"
    },
    {
      "id": "retainer-standard",
      "layer": "package",
      "vertical": "retain",
      "name": "Retainer Standard (mo)",
      "price": "$1,499",
      "amount_cents": 149900,
      "blurb": "Monthly ops + priority CS.",
      "paymentLink": "https://buy.stripe.com/9B65kE0k9fqmdFyeLU0Fi19",
      "recurring": "month"
    },
    {
      "id": "retainer-school",
      "layer": "package",
      "vertical": "retain",
      "name": "School Retainer (mo)",
      "price": "$2,999",
      "amount_cents": 299900,
      "blurb": "Ongoing classroom AI support.",
      "paymentLink": "https://buy.stripe.com/28E8wQ7MB91Y44YgU20Fi1a",
      "recurring": "month"
    },
    {
      "id": "media-pack-5",
      "layer": "micro",
      "vertical": "media",
      "name": "Media Pack 5",
      "price": "$5",
      "amount_cents": 500,
      "blurb": "5 image credits for Studio.",
      "paymentLink": "https://buy.stripe.com/bJe9AU2shemi44YbzI0Fi1b",
      "featured": true
    },
    {
      "id": "media-pack-20",
      "layer": "micro",
      "vertical": "media",
      "name": "Media Pack 20",
      "price": "$15",
      "amount_cents": 1500,
      "blurb": "20 image credits \u2014 best starter media pack.",
      "paymentLink": "https://buy.stripe.com/14AcN63wlguq9pi9rA0Fi1c",
      "featured": true
    },
    {
      "id": "media-pack-50",
      "layer": "micro",
      "vertical": "media",
      "name": "Media Pack 50",
      "price": "$30",
      "amount_cents": 3000,
      "blurb": "50 image credits for creators.",
      "paymentLink": "https://buy.stripe.com/4gM4gAc2Ra627hafPY0Fi1d"
    },
    {
      "id": "media-pack-100",
      "layer": "micro",
      "vertical": "media",
      "name": "Media Pack 100",
      "price": "$50",
      "amount_cents": 5000,
      "blurb": "100 image credits \u2014 power pack.",
      "paymentLink": "https://buy.stripe.com/28E8wQff37XU8leeLU0Fi1e"
    },
    {
      "id": "image-single",
      "layer": "micro",
      "vertical": "media",
      "name": "Single image credit",
      "price": "$1.50",
      "amount_cents": 150,
      "blurb": "One Studio image generation.",
      "paymentLink": "https://buy.stripe.com/bJe4gA1od1zwdFy6fo0Fi1f"
    },
    {
      "id": "image-burst-10",
      "layer": "micro",
      "vertical": "media",
      "name": "Image burst 10",
      "price": "$9",
      "amount_cents": 900,
      "blurb": "10 generations in one pack.",
      "paymentLink": "https://buy.stripe.com/4gM5kE3wl3HE0SMfPY0Fi1g"
    }
  ]
};
