/**
 * AUTO-GENERATED by epic-desk/scripts/generate_config.py — do not hand-edit SKUs.
 * Payment links come from epic-desk/catalog.live.json (public URLs only).
 */
window.EPIC_CONFIG = {
  "brand": "Epic Tech AI",
  "product": "Epic Everywhere",
  "contactEmail": "epictechai@gmail.com",
  "xUrl": "https://x.com/EpicTechAI",
  "successPath": "./success.html",
  "legalPath": "./legal/",
  "catalogVersion": "2026-07-13",
  "skuCount": 60,
  "skus": [
    {
      "id": "human-ticket",
      "layer": "micro",
      "vertical": "community",
      "name": "Human / entry ticket",
      "price": "$0.99",
      "amount_cents": 99,
      "blurb": "Low-friction entry pass.",
      "paymentLink": null
    },
    {
      "id": "tip-3",
      "layer": "micro",
      "vertical": "community",
      "name": "Support tip $3",
      "price": "$3",
      "amount_cents": 300,
      "blurb": "Tip the CS desk \u2014 keeps free guidance alive.",
      "paymentLink": null
    },
    {
      "id": "tip-5",
      "layer": "micro",
      "vertical": "community",
      "name": "Support tip $5",
      "price": "$5",
      "amount_cents": 500,
      "blurb": "Bigger tip for deeper free help.",
      "paymentLink": null
    },
    {
      "id": "ai-starter-pack",
      "layer": "micro",
      "vertical": "general",
      "name": "AI Starter Pack",
      "price": "$2.99",
      "amount_cents": 299,
      "blurb": "10 guided prompts + personal starter plan.",
      "paymentLink": null
    },
    {
      "id": "ai-starter-pack-pro",
      "layer": "micro",
      "vertical": "general",
      "name": "AI Starter Pack Pro",
      "price": "$7.99",
      "amount_cents": 799,
      "blurb": "30 prompts + role plan + 48h text follow-up.",
      "paymentLink": null
    },
    {
      "id": "cs-text-burst",
      "layer": "micro",
      "vertical": "general",
      "name": "Text CS Burst (24h)",
      "price": "$4.99",
      "amount_cents": 499,
      "blurb": "24h text customer success on your setup.",
      "paymentLink": null,
      "featured": true
    },
    {
      "id": "cs-text-burst-72",
      "layer": "micro",
      "vertical": "general",
      "name": "Text CS Burst (72h)",
      "price": "$9.99",
      "amount_cents": 999,
      "blurb": "3-day text CS window for harder setups.",
      "paymentLink": null
    },
    {
      "id": "workflow-fix",
      "layer": "micro",
      "vertical": "general",
      "name": "Workflow Fix",
      "price": "$9",
      "amount_cents": 900,
      "blurb": "One pain \u2192 one reusable AI workflow.",
      "paymentLink": null,
      "featured": true
    },
    {
      "id": "workflow-fix-3",
      "layer": "micro",
      "vertical": "general",
      "name": "Workflow Fix Bundle (3)",
      "price": "$24",
      "amount_cents": 2400,
      "blurb": "Three workflows for home, work, and side project.",
      "paymentLink": null
    },
    {
      "id": "credit-5",
      "layer": "micro",
      "vertical": "credits",
      "name": "Credit Pack 5",
      "price": "$5",
      "amount_cents": 500,
      "blurb": "5 credits toward text CS.",
      "paymentLink": null
    },
    {
      "id": "credit-10",
      "layer": "micro",
      "vertical": "credits",
      "name": "Credit Pack 10",
      "price": "$10",
      "amount_cents": 1000,
      "blurb": "10 credits toward text CS / future voice.",
      "paymentLink": null
    },
    {
      "id": "credit-25",
      "layer": "micro",
      "vertical": "credits",
      "name": "Credit Pack 25",
      "price": "$22",
      "amount_cents": 2200,
      "blurb": "25 credits \u2014 best micro value.",
      "paymentLink": null
    },
    {
      "id": "credit-50",
      "layer": "micro",
      "vertical": "credits",
      "name": "Credit Pack 50",
      "price": "$40",
      "amount_cents": 4000,
      "blurb": "50 credits for power users.",
      "paymentLink": null
    },
    {
      "id": "prompt-audit",
      "layer": "micro",
      "vertical": "general",
      "name": "Prompt Audit",
      "price": "$7",
      "amount_cents": 700,
      "blurb": "We rewrite your 5 worst prompts into winners.",
      "paymentLink": null
    },
    {
      "id": "tool-stack-map",
      "layer": "micro",
      "vertical": "general",
      "name": "Tool Stack Map",
      "price": "$12",
      "amount_cents": 1200,
      "blurb": "Which AI tools you actually need \u2014 one page plan.",
      "paymentLink": null
    },
    {
      "id": "student-homework-kit",
      "layer": "micro",
      "vertical": "student",
      "name": "Student Homework Kit",
      "price": "$4.99",
      "amount_cents": 499,
      "blurb": "Subject prompts + integrity-safe study method.",
      "paymentLink": null
    },
    {
      "id": "student-essay-coach",
      "layer": "micro",
      "vertical": "student",
      "name": "Essay Coach Pack",
      "price": "$9",
      "amount_cents": 900,
      "blurb": "Outline, thesis, revision loop \u2014 you still write it.",
      "paymentLink": null
    },
    {
      "id": "student-stem-pack",
      "layer": "micro",
      "vertical": "student",
      "name": "STEM Study Pack",
      "price": "$9",
      "amount_cents": 900,
      "blurb": "Math/science problem-solving with AI, step-by-step.",
      "paymentLink": null
    },
    {
      "id": "student-college-apps",
      "layer": "micro",
      "vertical": "student",
      "name": "College Apps AI Kit",
      "price": "$15",
      "amount_cents": 1500,
      "blurb": "Brainstorm + structure essays ethically.",
      "paymentLink": null
    },
    {
      "id": "parent-safety-kit",
      "layer": "micro",
      "vertical": "parent",
      "name": "Parent AI Safety Kit",
      "price": "$4.99",
      "amount_cents": 499,
      "blurb": "Family rules, tools, and homework boundaries.",
      "paymentLink": null
    },
    {
      "id": "parent-homework-coach",
      "layer": "micro",
      "vertical": "parent",
      "name": "Parent Homework Coach",
      "price": "$9",
      "amount_cents": 900,
      "blurb": "Help your kid use AI without doing it for them.",
      "paymentLink": null
    },
    {
      "id": "parent-device-setup",
      "layer": "micro",
      "vertical": "parent",
      "name": "Family Device AI Setup",
      "price": "$12",
      "amount_cents": 1200,
      "blurb": "Phone/laptop AI apps configured for the household.",
      "paymentLink": null
    },
    {
      "id": "teacher-classroom-kit",
      "layer": "micro",
      "vertical": "teacher",
      "name": "Teacher Classroom Kit",
      "price": "$9",
      "amount_cents": 900,
      "blurb": "One week of AI lesson assist prompts + policy notes.",
      "paymentLink": null
    },
    {
      "id": "teacher-rubric-pack",
      "layer": "micro",
      "vertical": "teacher",
      "name": "Rubric & Feedback Pack",
      "price": "$12",
      "amount_cents": 1200,
      "blurb": "Faster feedback loops that stay human-led.",
      "paymentLink": null
    },
    {
      "id": "teacher-pd-micro",
      "layer": "micro",
      "vertical": "teacher",
      "name": "Teacher PD Micro",
      "price": "$19",
      "amount_cents": 1900,
      "blurb": "90-min async PD plan you can run with peers.",
      "paymentLink": null
    },
    {
      "id": "founder-offer-kit",
      "layer": "micro",
      "vertical": "founder",
      "name": "Founder Offer Kit",
      "price": "$15",
      "amount_cents": 1500,
      "blurb": "Positioning + offer page outline with AI.",
      "paymentLink": null
    },
    {
      "id": "founder-outreach-pack",
      "layer": "micro",
      "vertical": "founder",
      "name": "Outreach Pack",
      "price": "$12",
      "amount_cents": 1200,
      "blurb": "20 personalized outreach templates + system.",
      "paymentLink": null
    },
    {
      "id": "founder-support-bot-plan",
      "layer": "micro",
      "vertical": "founder",
      "name": "Support Bot Plan",
      "price": "$19",
      "amount_cents": 1900,
      "blurb": "CS macros + AI assist design for your product.",
      "paymentLink": null
    },
    {
      "id": "smb-email-overhaul",
      "layer": "micro",
      "vertical": "smb",
      "name": "Email Overhaul",
      "price": "$9",
      "amount_cents": 900,
      "blurb": "Rewrite your core business emails with AI.",
      "paymentLink": null
    },
    {
      "id": "smb-review-replies",
      "layer": "micro",
      "vertical": "smb",
      "name": "Review Reply Pack",
      "price": "$7",
      "amount_cents": 700,
      "blurb": "Google/Yelp reply system for local business.",
      "paymentLink": null
    },
    {
      "id": "smb-sop-pack",
      "layer": "micro",
      "vertical": "smb",
      "name": "SOP Starter Pack",
      "price": "$15",
      "amount_cents": 1500,
      "blurb": "3 SOPs drafted with AI for your ops.",
      "paymentLink": null
    },
    {
      "id": "creator-content-engine",
      "layer": "micro",
      "vertical": "creator",
      "name": "Content Engine Micro",
      "price": "$12",
      "amount_cents": 1200,
      "blurb": "7-day content system for X/Shorts/LinkedIn.",
      "paymentLink": null
    },
    {
      "id": "creator-script-pack",
      "layer": "micro",
      "vertical": "creator",
      "name": "Script Pack (10)",
      "price": "$9",
      "amount_cents": 900,
      "blurb": "Ten short-form scripts in your voice.",
      "paymentLink": null
    },
    {
      "id": "career-resume-pack",
      "layer": "micro",
      "vertical": "career",
      "name": "Resume + LinkedIn Pack",
      "price": "$15",
      "amount_cents": 1500,
      "blurb": "AI-assisted resume + profile rewrite.",
      "paymentLink": null
    },
    {
      "id": "career-interview-kit",
      "layer": "micro",
      "vertical": "career",
      "name": "Interview Kit",
      "price": "$12",
      "amount_cents": 1200,
      "blurb": "STAR stories + mock questions with AI.",
      "paymentLink": null
    },
    {
      "id": "career-portfolio-plan",
      "layer": "micro",
      "vertical": "career",
      "name": "Portfolio Plan",
      "price": "$9",
      "amount_cents": 900,
      "blurb": "Ship a portfolio narrative in one weekend.",
      "paymentLink": null
    },
    {
      "id": "senior-basics",
      "layer": "micro",
      "vertical": "senior",
      "name": "AI Basics for Adults",
      "price": "$4.99",
      "amount_cents": 499,
      "blurb": "Patient, large-print style starter for non-tech adults.",
      "paymentLink": null
    },
    {
      "id": "senior-phone-prep",
      "layer": "micro",
      "vertical": "senior",
      "name": "Phone Session Prep",
      "price": "$3",
      "amount_cents": 300,
      "blurb": "Prep worksheet before a phone coaching call.",
      "paymentLink": null
    },
    {
      "id": "phone-15",
      "layer": "session",
      "vertical": "live",
      "name": "Phone coaching 15m",
      "price": "$15",
      "amount_cents": 1500,
      "blurb": "Guided AI setup call.",
      "paymentLink": null,
      "phase": "Phase 2"
    },
    {
      "id": "phone-30",
      "layer": "session",
      "vertical": "live",
      "name": "Phone coaching 30m",
      "price": "$29",
      "amount_cents": 2900,
      "blurb": "Deep-dive coaching call.",
      "paymentLink": null,
      "featured": true,
      "phase": "Phase 2"
    },
    {
      "id": "phone-60",
      "layer": "session",
      "vertical": "live",
      "name": "Phone coaching 60m",
      "price": "$55",
      "amount_cents": 5500,
      "blurb": "Full-hour implementation call.",
      "paymentLink": null,
      "phase": "Phase 2"
    },
    {
      "id": "video-tutor-25",
      "layer": "session",
      "vertical": "live",
      "name": "Live video tutor 25m",
      "price": "$25",
      "amount_cents": 2500,
      "blurb": "Screen-share. Do the task together.",
      "paymentLink": null,
      "featured": true,
      "phase": "Phase 3"
    },
    {
      "id": "video-tutor-50",
      "layer": "session",
      "vertical": "live",
      "name": "Live video tutor 50m",
      "price": "$49",
      "amount_cents": 4900,
      "blurb": "Project session with reusable pack.",
      "paymentLink": null,
      "phase": "Phase 3"
    },
    {
      "id": "video-tutor-90",
      "layer": "session",
      "vertical": "live",
      "name": "Live video tutor 90m",
      "price": "$89",
      "amount_cents": 8900,
      "blurb": "Deep build session.",
      "paymentLink": null,
      "phase": "Phase 3"
    },
    {
      "id": "class-seat",
      "layer": "session",
      "vertical": "live",
      "name": "Group class seat",
      "price": "$12",
      "amount_cents": 1200,
      "blurb": "Weekly AI-for-everyone class.",
      "paymentLink": null,
      "phase": "Phase 3"
    },
    {
      "id": "class-seat-4pack",
      "layer": "session",
      "vertical": "live",
      "name": "Group class 4-pack",
      "price": "$40",
      "amount_cents": 4000,
      "blurb": "Four class seats.",
      "paymentLink": null,
      "phase": "Phase 3"
    },
    {
      "id": "office-hours-dropin",
      "layer": "session",
      "vertical": "live",
      "name": "Office hours drop-in",
      "price": "$19",
      "amount_cents": 1900,
      "blurb": "Join next open office hours block.",
      "paymentLink": null,
      "phase": "Phase 2"
    },
    {
      "id": "pilot-landing",
      "layer": "package",
      "vertical": "build",
      "name": "Pilot Landing",
      "price": "$750",
      "amount_cents": 75000,
      "blurb": "One-page site + form on Vercel.",
      "paymentLink": null,
      "featured": true
    },
    {
      "id": "pilot-landing-plus",
      "layer": "package",
      "vertical": "build",
      "name": "Pilot Landing Plus",
      "price": "$1,250",
      "amount_cents": 125000,
      "blurb": "Landing + Stripe micros + basic analytics.",
      "paymentLink": null
    },
    {
      "id": "agent-ops-setup",
      "layer": "package",
      "vertical": "build",
      "name": "Agent Ops Setup",
      "price": "$1,500",
      "amount_cents": 150000,
      "blurb": "Slack + Stripe + agent ops wired.",
      "paymentLink": null,
      "featured": true
    },
    {
      "id": "agent-ops-setup-pro",
      "layer": "package",
      "vertical": "build",
      "name": "Agent Ops Setup Pro",
      "price": "$3,500",
      "amount_cents": 350000,
      "blurb": "Ops setup + 2 custom workflows + 30d CS.",
      "paymentLink": null
    },
    {
      "id": "school-pilot",
      "layer": "package",
      "vertical": "education",
      "name": "School Pilot",
      "price": "$2,500",
      "amount_cents": 250000,
      "blurb": "Classroom AI adoption pilot.",
      "paymentLink": null,
      "featured": true
    },
    {
      "id": "school-pilot-district",
      "layer": "package",
      "vertical": "education",
      "name": "School Pilot (multi-site)",
      "price": "$7,500",
      "amount_cents": 750000,
      "blurb": "Multi-site pilot + teacher PD outline.",
      "paymentLink": null
    },
    {
      "id": "creator-brand-kit",
      "layer": "package",
      "vertical": "creator",
      "name": "Creator Brand Kit Build",
      "price": "$990",
      "amount_cents": 99000,
      "blurb": "Positioning, content system, 30-day calendar.",
      "paymentLink": null
    },
    {
      "id": "smb-ai-ops",
      "layer": "package",
      "vertical": "smb",
      "name": "SMB AI Ops Sprint",
      "price": "$1,990",
      "amount_cents": 199000,
      "blurb": "2-week ops automation sprint for local/online SMB.",
      "paymentLink": null
    },
    {
      "id": "career-sprint",
      "layer": "package",
      "vertical": "career",
      "name": "Career Sprint",
      "price": "$499",
      "amount_cents": 49900,
      "blurb": "2-week job search system with AI.",
      "paymentLink": null
    },
    {
      "id": "custom-work-deposit",
      "layer": "package",
      "vertical": "build",
      "name": "Custom Work Deposit",
      "price": "$500",
      "amount_cents": 50000,
      "blurb": "Kickoff deposit for scoped custom work.",
      "paymentLink": null
    },
    {
      "id": "retainer-lite",
      "layer": "package",
      "vertical": "retain",
      "name": "Retainer Lite (mo)",
      "price": "$499",
      "amount_cents": 49900,
      "blurb": "Monthly async CS + 2 workflows.",
      "paymentLink": null,
      "recurring": "month"
    },
    {
      "id": "retainer-standard",
      "layer": "package",
      "vertical": "retain",
      "name": "Retainer Standard (mo)",
      "price": "$1,499",
      "amount_cents": 149900,
      "blurb": "Monthly ops + priority CS.",
      "paymentLink": null,
      "recurring": "month"
    },
    {
      "id": "retainer-school",
      "layer": "package",
      "vertical": "retain",
      "name": "School Retainer (mo)",
      "price": "$2,999",
      "amount_cents": 299900,
      "blurb": "Ongoing classroom AI support.",
      "paymentLink": null,
      "recurring": "month"
    }
  ]
};
